services:
  api: 
   image: projeto 
   ports:
   - '8080:8080'
   depends_on:
    - db
  
  db: 
    image: mysql:8.3.0
    ports:
     - '3307:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Prosper135
      MYSQL_DATABASE: produtos
      MYSQL_USER: jailine
      MYSQL_PASSWORD: Prosper135
      
  
   
   
  